-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "DP-1", mode = "2560x1440@144.01", position = "0x0", scale = 1.00, bitdepth = 10, vrr = 1 })
hl.monitor({ output = "DP-2", mode = "2560x1440@180.06", position = "2560x-1152", scale = 1.00, bitdepth = 10, vrr = 2, transform = 3 })
hl.monitor({ output = "DP-3", mode = "2560x1440@180.06", position = "0x-1440", scale = 1.00, bitdepth = 10, vrr = 2 })
