-- hyprbars is loaded at runtime via hyprctl (see hyprland.lua), so it isn't
-- registered yet on the very first config parse; skip until it's available.
if hl.plugin == nil or hl.plugin.hyprbars == nil then
    return
end

-- noctalia.lua is generated by noctalia on first login, so it may not exist yet
local ok, noctalia = pcall(require, "noctalia")
local colors = ok and noctalia.colors or {
    primary = "#a6e3a1",
    surface = "#1e1e2e",
    on_surface = "#cdd6f4",
    secondary = "#f9e2af",
    on_secondary = "#1e1e2e",
    error = "#f38ba8",
    on_error = "#1e1e2e",
}

-- Hyprland expects "rgb(RRGGBB)", noctalia gives "#RRGGBB"
local function to_rgb(hex)
    return "rgb(" .. hex:gsub("^#", "") .. ")"
end

hl.config({
    plugin = {
        hyprbars = {
            bar_height = 28,
            bar_color = to_rgb(colors.surface),
            ["col.text"] = to_rgb(colors.on_surface),
            bar_text_size = 11,
            bar_text_align = "left",
            bar_padding = 10,
            bar_button_padding = 8,
        },
    },
})

-- Buttons render right-to-left in the order they are added below.

-- Maximize the active window, click again to restore its previous size
hl.plugin.hyprbars.add_button({
    bg_color = to_rgb(colors.primary),
    fg_color = to_rgb(colors.on_surface),
    size = 10,
    icon = "",
    action = [[hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })']],
})

-- Send the active window to the scratchpad
hl.plugin.hyprbars.add_button({
    bg_color = to_rgb(colors.secondary),
    fg_color = to_rgb(colors.on_secondary),
    size = 10,
    icon = "",
    action = [[hyprctl dispatch 'hl.dsp.window.move({ workspace = "special:scratchpad" })']],
})

-- Close the active window
hl.plugin.hyprbars.add_button({
    bg_color = to_rgb(colors.error),
    fg_color = to_rgb(colors.on_error),
    size = 10,
    icon = "󰖭",
    action = [[hyprctl dispatch 'hl.dsp.window.close()']],
})

