Window.SetBackgroundTopColor(0.012, 0.024, 0.055);
Window.SetBackgroundBottomColor(0.012, 0.024, 0.055);

logo.original_image = Image("logo.png");
logo.image = logo.original_image.Scale(240, 240);
logo.sprite = Sprite(logo.image);
logo.sprite.SetPosition(
    Window.GetX() + Window.GetWidth() / 2 - logo.image.GetWidth() / 2,
    Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2,
    0
);

fun refresh_callback() {
    logo.sprite.SetX(Window.GetX() + Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
    logo.sprite.SetY(Window.GetY() + Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
}

Plymouth.SetRefreshFunction(refresh_callback);