font-family = FiraCode Nerd Font
background-opacity = 0.9
window-padding-x = 15
window-padding-y = 15
window-padding-balance = true
window-decoration = auto
shell-integration = detect
mouse-hide-while-typing = true
custom-shader = /usr/share/srvb/ghostty/shaders/cursor_tail.glsl
custom-shader-animation = always
